//! `mlsh adopt <url>` — join an existing cluster from an invite URL.

use anyhow::{Context, Result};
use colored::Colorize;

use super::bootstrap::{self, BootstrapInput};

/// Default QUIC port for `mlsh://` URLs (same as HTTPS).
const DEFAULT_SIGNAL_PORT: u16 = 443;

pub async fn handle_adopt(url: &str, name_override: Option<&str>) -> Result<()> {
    let (signal_host, payload) = parse_adopt_url(url)?;

    println!("{}", "Joining cluster via QUIC...".cyan().bold());
    println!("  Signal: {}", signal_host);

    let invite = mlsh_crypto::invite::decode_invite_payload(&payload)
        .map_err(|e| anyhow::anyhow!("Invalid invite: {}", e))?;

    let signal_fingerprint = invite.signal_fingerprint.unwrap_or_default();
    if signal_fingerprint.is_empty() {
        anyhow::bail!(
            "Invite does not contain signal_fingerprint.\n\
             The invite may have been generated by an older version. \
             Ask the admin to re-generate it."
        );
    }
    let root_fingerprint = invite.root_fingerprint.unwrap_or_default();

    let node_id = bootstrap::generate_node_id();
    let display_name = bootstrap::default_display_name(name_override);
    let signal_endpoint = bootstrap::ensure_port(&signal_host, DEFAULT_SIGNAL_PORT);

    let out = bootstrap::run(BootstrapInput {
        cluster_name: &invite.cluster_name,
        cluster_id: &invite.cluster_id,
        signal_endpoint: &signal_endpoint,
        signal_fingerprint: &signal_fingerprint,
        root_fingerprint: &root_fingerprint,
        node_id: &node_id,
        display_name: &display_name,
        pre_auth_token: &payload,
        roles: &["node"],
    })
    .await?;

    println!();
    println!("{}", "Cluster joined successfully!".green().bold());
    println!("  Cluster:  {}", invite.cluster_name);
    println!("  Overlay:  {}", out.overlay_ip);
    println!("  Identity: {}", out.identity_dir.display());
    println!();
    println!(
        "Connect with: {}",
        format!("mlsh connect {}", invite.cluster_name).bold()
    );
    Ok(())
}

/// Parse an adopt URL: `mlsh://<host>/adopt/<payload>`.
fn parse_adopt_url(url: &str) -> Result<(String, String)> {
    let rest = url
        .strip_prefix("mlsh://")
        .or_else(|| url.strip_prefix("https://"))
        .context("Invalid URL scheme. Expected mlsh:// or https://")?;
    let parts: Vec<&str> = rest.splitn(2, "/adopt/").collect();
    if parts.len() == 2 && !parts[0].is_empty() && !parts[1].is_empty() {
        Ok((parts[0].to_string(), parts[1].to_string()))
    } else {
        anyhow::bail!("Invalid adopt URL format. Expected: mlsh://<host>/adopt/<payload>")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_adopt_url_basic() {
        let (host, payload) =
            parse_adopt_url("mlsh://signal.example.com/adopt/eyJjbHVzdGVy").unwrap();
        assert_eq!(host, "signal.example.com");
        assert_eq!(payload, "eyJjbHVzdGVy");
    }

    #[test]
    fn parse_adopt_url_with_port() {
        let (host, payload) =
            parse_adopt_url("mlsh://signal.example.com:4433/adopt/abc123").unwrap();
        assert_eq!(host, "signal.example.com:4433");
        assert_eq!(payload, "abc123");
    }

    #[test]
    fn parse_adopt_url_invalid() {
        assert!(parse_adopt_url("mlsh://host/adopt/").is_err());
        assert!(parse_adopt_url("mlsh:///adopt/token").is_err());
        assert!(parse_adopt_url("not-a-url").is_err());
    }
}
