//! `mlsh adopt <url>` — join a cluster using an invite URL.
//!
//! Flow:
//! 1. Parse invite URL → signal host + base64 payload
//! 2. Extract signal_fingerprint from invite (for QUIC cert verification)
//! 3. Generate node identity (self-signed cert + fingerprint)
//! 4. Connect to signal via QUIC → send Adopt message
//! 5. Receive AdoptOk with overlay IP + node_token
//! 6. Save cluster config

use anyhow::{Context, Result};
use colored::Colorize;
use std::net::SocketAddr;
use std::sync::Arc;

/// Default QUIC port for mlsh:// URLs (same as HTTPS).
const DEFAULT_SIGNAL_PORT: u16 = 443;

/// Handle `mlsh adopt <url> [--name <name>]`.
pub async fn handle_adopt(url: &str, name_override: Option<&str>) -> Result<()> {
    let (signal_host, payload) = parse_adopt_url(url)?;

    println!("{}", "Joining cluster via QUIC...".cyan().bold());
    println!("  Signal: {}", signal_host);

    // Decode the invite payload (CBOR format) to extract fields
    let invite_payload = mlsh_crypto::invite::decode_invite_payload(&payload)
        .map_err(|e| anyhow::anyhow!("Invalid invite: {}", e))?;

    let cluster_id = invite_payload.cluster_id;
    let cluster_name = invite_payload.cluster_name;
    let invite_token = payload.clone();
    let signal_fingerprint = invite_payload.signal_fingerprint.unwrap_or_default();
    let root_fingerprint = invite_payload.root_fingerprint.unwrap_or_default();

    if signal_fingerprint.is_empty() {
        anyhow::bail!(
            "Invite does not contain signal_fingerprint.\n\
             The invite may have been generated by an older version. Ask the admin to re-generate it."
        );
    }

    // Generate or load node identity
    let config_dir = crate::config::config_dir()?;
    let identity_dir = config_dir.join("identity");
    let node_id = name_override
        .map(String::from)
        .unwrap_or_else(|| whoami::hostname().unwrap_or_else(|_| "node".to_string()));
    let identity = mlsh_crypto::identity::load_or_generate(&identity_dir, &node_id)
        .map_err(|e| anyhow::anyhow!("Failed to generate identity: {}", e))?;

    println!("  Node ID:     {}", node_id);
    println!("  Fingerprint: {}...", &identity.fingerprint[..16]);

    // Extract public key from cert
    use base64::Engine;
    let public_key = mlsh_crypto::invite::extract_public_key_from_cert_pem(&identity.cert_pem)
        .map(|pk| base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(&pk))
        .unwrap_or_default();

    // Connect to signal via QUIC (verified by fingerprint from invite)
    let signal_endpoint = ensure_port(&signal_host, DEFAULT_SIGNAL_PORT);
    let addr = resolve_addr(&signal_endpoint)?;
    let conn = connect_to_signal(addr, &signal_endpoint, &signal_fingerprint, &identity).await?;

    // Send Adopt message
    let (mut send, mut recv) = conn
        .open_bi()
        .await
        .context("Failed to open signal stream")?;

    use mlsh_protocol::framing;
    use mlsh_protocol::messages::{ServerMessage, StreamMessage};

    let adopt_msg = StreamMessage::Adopt {
        cluster_id: cluster_id.clone(),
        pre_auth_token: invite_token,
        fingerprint: identity.fingerprint.clone(),
        node_id: node_id.clone(),
        public_key,
        expires_at: 0,
        admission_cert: String::new(),
    };
    framing::write_msg(&mut send, &adopt_msg).await?;

    let resp: ServerMessage = framing::read_msg(&mut recv).await?;
    conn.close(quinn::VarInt::from_u32(0), b"done");

    let (overlay_ip, overlay_subnet, resp_cluster_id) = match resp {
        ServerMessage::AdoptOk {
            overlay_ip,
            overlay_subnet,
            cluster_id: cid,
            ..
        } => (overlay_ip, overlay_subnet, cid),
        ServerMessage::Error { code, message } => {
            anyhow::bail!("Adopt failed: {} ({})", message, code);
        }
        other => {
            anyhow::bail!("Unexpected response: {:?}", other);
        }
    };

    // Save cluster config
    let clusters_dir = config_dir.join("clusters");
    std::fs::create_dir_all(&clusters_dir)?;

    let cluster_toml = format!(
        "[cluster]\n\
         name = \"{cluster_name}\"\n\
         id = \"{resp_cluster_id}\"\n\
         mode = \"mtls\"\n\
         signal_endpoint = \"{signal_endpoint}\"\n\
         signal_fingerprint = \"{signal_fingerprint}\"\n\
         root_fingerprint = \"{root_fingerprint}\"\n\
         \n\
         [node_auth]\n\
         node_id = \"{node_id}\"\n\
         fingerprint = \"{fp}\"\n\
         \n\
         [overlay]\n\
         ip = \"{overlay_ip}\"\n\
         subnet = \"{overlay_subnet}\"\n",
        fp = identity.fingerprint,
    );

    let cluster_file = clusters_dir.join(format!("{}.toml", cluster_name));
    std::fs::write(&cluster_file, &cluster_toml)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&cluster_file, std::fs::Permissions::from_mode(0o600))?;
    }

    println!();
    println!("{}", "Cluster joined successfully!".green().bold());
    println!("  Cluster:  {}", cluster_name);
    println!("  Overlay:  {}", overlay_ip);
    println!("  Identity: {}", identity_dir.display());
    println!();
    println!(
        "Connect with: {}",
        format!("mlsh connect {}", cluster_name).bold()
    );

    Ok(())
}

// --- URL parsing

/// Parse an adopt URL: `mlsh://<host>/adopt/<payload>`.
fn parse_adopt_url(url: &str) -> Result<(String, String)> {
    let rest = url
        .strip_prefix("mlsh://")
        .or_else(|| url.strip_prefix("https://"))
        .context("Invalid URL scheme. Expected mlsh:// or https://")?;
    let parts: Vec<&str> = rest.splitn(2, "/adopt/").collect();
    if parts.len() == 2 && !parts[0].is_empty() && !parts[1].is_empty() {
        Ok((parts[0].to_string(), parts[1].to_string()))
    } else {
        anyhow::bail!("Invalid adopt URL format. Expected: mlsh://<host>/adopt/<payload>")
    }
}

/// Ensure the endpoint has a port suffix.
fn ensure_port(host: &str, default_port: u16) -> String {
    if host.contains(':') {
        host.to_string()
    } else {
        format!("{}:{}", host, default_port)
    }
}

// --- QUIC helpers

async fn connect_to_signal(
    addr: SocketAddr,
    endpoint_str: &str,
    signal_fingerprint: &str,
    identity: &mlsh_crypto::identity::NodeIdentity,
) -> Result<quinn::Connection> {
    let cert_der = mlsh_crypto::identity::pem_to_der_pub(&identity.cert_pem)
        .map_err(|e| anyhow::anyhow!("Invalid cert PEM: {}", e))?;
    let cert = rustls::pki_types::CertificateDer::from(cert_der);
    let key = rustls_pemfile::private_key(&mut identity.key_pem.as_bytes())
        .context("Failed to parse identity key")?
        .context("No private key in PEM")?;

    let mut tls_config = rustls::ClientConfig::builder()
        .dangerous()
        .with_custom_certificate_verifier(Arc::new(
            crate::quic::verifier::FingerprintVerifier::new(signal_fingerprint),
        ))
        .with_client_auth_cert(vec![cert], key)
        .context("Failed to set client auth cert")?;
    tls_config.alpn_protocols = vec![b"mlsh-signal".to_vec()];

    let client_config = quinn::ClientConfig::new(Arc::new(
        quinn::crypto::rustls::QuicClientConfig::try_from(tls_config)
            .context("Failed to create QUIC TLS config")?,
    ));

    let bind_addr: SocketAddr = if addr.is_ipv6() {
        "[::]:0".parse().unwrap()
    } else {
        "0.0.0.0:0".parse().unwrap()
    };
    let mut endpoint = quinn::Endpoint::client(bind_addr)?;
    endpoint.set_default_client_config(client_config);

    let sni_host = endpoint_str.split(':').next().unwrap_or(endpoint_str);

    let conn = tokio::time::timeout(
        std::time::Duration::from_secs(10),
        endpoint.connect(addr, sni_host)?,
    )
    .await
    .map_err(|_| anyhow::anyhow!("Timed out connecting to signal"))?
    .context("Failed to connect to signal")?;

    Ok(conn)
}

fn resolve_addr(endpoint: &str) -> Result<SocketAddr> {
    if let Ok(addr) = endpoint.parse::<SocketAddr>() {
        return Ok(addr);
    }
    let (host, port) = endpoint.rsplit_once(':').unwrap_or((endpoint, "4433"));
    let port: u16 = port.parse().unwrap_or(4433);
    use std::net::ToSocketAddrs;
    (host, port)
        .to_socket_addrs()?
        .find(|a| a.is_ipv4())
        .or_else(|| {
            (host, port)
                .to_socket_addrs()
                .ok()
                .and_then(|mut a| a.next())
        })
        .context(format!("Failed to resolve: {}", endpoint))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_adopt_url_basic() {
        let (host, payload) =
            parse_adopt_url("mlsh://signal.example.com/adopt/eyJjbHVzdGVy").unwrap();
        assert_eq!(host, "signal.example.com");
        assert_eq!(payload, "eyJjbHVzdGVy");
    }

    #[test]
    fn parse_adopt_url_with_port() {
        let (host, payload) =
            parse_adopt_url("mlsh://signal.example.com:4433/adopt/abc123").unwrap();
        assert_eq!(host, "signal.example.com:4433");
        assert_eq!(payload, "abc123");
    }

    #[test]
    fn parse_adopt_url_invalid() {
        assert!(parse_adopt_url("mlsh://host/adopt/").is_err());
        assert!(parse_adopt_url("mlsh:///adopt/token").is_err());
        assert!(parse_adopt_url("not-a-url").is_err());
    }

    #[test]
    fn ensure_port_adds_default() {
        assert_eq!(
            ensure_port("signal.example.com", 4433),
            "signal.example.com:4433"
        );
        assert_eq!(
            ensure_port("signal.example.com:5555", 4433),
            "signal.example.com:5555"
        );
    }
}
